# https://github.com/mapbox/MapboxNavigation.swift#mapboxnavigationswift

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zero' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!

	# Pods for zero
	pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'
	pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'
	pod 'Mapbox-iOS-SDK-symbols', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.4.0/platform/ios/Mapbox-iOS-SDK-symbols.podspec'

end

target 'zero WatchKit App' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!

	# Pods for zero WatchKit App

end

target 'zero WatchKit Extension' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!

	# Pods for zero WatchKit Extension

end
