# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zero' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zero

end

target 'zero WatchKit App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zero WatchKit App

end

target 'zero WatchKit Extension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zero WatchKit Extension

end
